### ISSUE TITLE
Need proper error handling when there is no kubeconfig to work with

### ISSUE THREAD

**Issue by sitaramkm** [jetstack/jsctl#23]
Had just deleted the cluster and there was no `kubeconfig`  to use. Running `jsctl clusters connect mycluster` causes a panic. 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x105bd9f20]

goroutine 1 [running]:
k8s.io/client-go/kubernetes.NewForConfig(0x105cab861?)
	k8s.io/client-go@v0.25.0/kubernetes/clientset.go:422 +0x20
github.com/jetstack/jsctl/internal/kubernetes.NewKubeConfigApplier({0x105cab861?, 0x14000448510?})
	github.com/jetstack/jsctl/internal/kubernetes/kubernetes.go:84 +0x2c
github.com/jetstack/jsctl/internal/command.clustersConnect.func1({0x1062001a0, 0x14000448510}, {0x14000512290?, 0x106c26e00?, 0x105fa41c0?})
	github.com/jetstack/jsctl/internal/command/clusters.go:68 +0x138
github.com/jetstack/jsctl/internal/command.run.func1(0x1400039ca00?, {0x14000512290, 0x1, 0x1})
	github.com/jetstack/jsctl/internal/command/command.go:73 +0x1d8
github.com/spf13/cobra.(*Command).execute(0x1400039ca00, {0x14000512270, 0x1, 0x1})
	github.com/spf13/cobra@v1.5.0/command.go:876 +0x4b8
github.com/spf13/cobra.(*Command).ExecuteC(0x1400002d900)
	github.com/spf13/cobra@v1.5.0/command.go:990 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.5.0/command.go:918
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.5.0/command.go:911
main.main()
	github.com/jetstack/jsctl/main.go:24 +0x11c

```

**Comment by charlieegan3** [comment]
https://github.com/jetstack/jsctl/pull/35 should address this.
